name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2

    - name: Build Windows
      run: bash ./make.sh
           mv ffk ffk.exe
      env:
        GOOS: windows

    - name: Build Linux
      run: bash ./make.sh
      env:
        GOOS: linux

    - name: 'Upload Artifact 1'
      uses: actions/upload-artifact@v3
      with:
        name: Linux FFK executable
        path: ffk
        retention-days: 5

    - name: 'Upload Artifact 2'
      uses: actions/upload-artifact@v3
      with:
        name: Windows FFK executable
        path: ffk.exe
        retention-days: 5
